package com.oyj.pojo;

import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.DEPT_ID
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.JOB_ID
     *
     * @mbggenerated
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.CARD_ID
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.POST_CODE
     *
     * @mbggenerated
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.TEL
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.QQ_NUM
     *
     * @mbggenerated
     */
    private String qqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.SEX
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.PARTY
     *
     * @mbggenerated
     */
    private String party;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.BIRTHDAY
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.RACE
     *
     * @mbggenerated
     */
    private String race;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.EDUCATION
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.SPECIALITY
     *
     * @mbggenerated
     */
    private String speciality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.HOBBY
     *
     * @mbggenerated
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.ID
     *
     * @return the value of employee_inf.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.ID
     *
     * @param id the value for employee_inf.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.DEPT_ID
     *
     * @return the value of employee_inf.DEPT_ID
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.DEPT_ID
     *
     * @param deptId the value for employee_inf.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.JOB_ID
     *
     * @return the value of employee_inf.JOB_ID
     *
     * @mbggenerated
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.JOB_ID
     *
     * @param jobId the value for employee_inf.JOB_ID
     *
     * @mbggenerated
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.NAME
     *
     * @return the value of employee_inf.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.NAME
     *
     * @param name the value for employee_inf.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.CARD_ID
     *
     * @return the value of employee_inf.CARD_ID
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.CARD_ID
     *
     * @param cardId the value for employee_inf.CARD_ID
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.ADDRESS
     *
     * @return the value of employee_inf.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.ADDRESS
     *
     * @param address the value for employee_inf.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.POST_CODE
     *
     * @return the value of employee_inf.POST_CODE
     *
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.POST_CODE
     *
     * @param postCode the value for employee_inf.POST_CODE
     *
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.TEL
     *
     * @return the value of employee_inf.TEL
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.TEL
     *
     * @param tel the value for employee_inf.TEL
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.PHONE
     *
     * @return the value of employee_inf.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.PHONE
     *
     * @param phone the value for employee_inf.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.QQ_NUM
     *
     * @return the value of employee_inf.QQ_NUM
     *
     * @mbggenerated
     */
    public String getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.QQ_NUM
     *
     * @param qqNum the value for employee_inf.QQ_NUM
     *
     * @mbggenerated
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum == null ? null : qqNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.EMAIL
     *
     * @return the value of employee_inf.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.EMAIL
     *
     * @param email the value for employee_inf.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.SEX
     *
     * @return the value of employee_inf.SEX
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.SEX
     *
     * @param sex the value for employee_inf.SEX
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.PARTY
     *
     * @return the value of employee_inf.PARTY
     *
     * @mbggenerated
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.PARTY
     *
     * @param party the value for employee_inf.PARTY
     *
     * @mbggenerated
     */
    public void setParty(String party) {
        this.party = party == null ? null : party.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.BIRTHDAY
     *
     * @return the value of employee_inf.BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.BIRTHDAY
     *
     * @param birthday the value for employee_inf.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.RACE
     *
     * @return the value of employee_inf.RACE
     *
     * @mbggenerated
     */
    public String getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.RACE
     *
     * @param race the value for employee_inf.RACE
     *
     * @mbggenerated
     */
    public void setRace(String race) {
        this.race = race == null ? null : race.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.EDUCATION
     *
     * @return the value of employee_inf.EDUCATION
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.EDUCATION
     *
     * @param education the value for employee_inf.EDUCATION
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.SPECIALITY
     *
     * @return the value of employee_inf.SPECIALITY
     *
     * @mbggenerated
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.SPECIALITY
     *
     * @param speciality the value for employee_inf.SPECIALITY
     *
     * @mbggenerated
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality == null ? null : speciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.HOBBY
     *
     * @return the value of employee_inf.HOBBY
     *
     * @mbggenerated
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.HOBBY
     *
     * @param hobby the value for employee_inf.HOBBY
     *
     * @mbggenerated
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.REMARK
     *
     * @return the value of employee_inf.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.REMARK
     *
     * @param remark the value for employee_inf.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.CREATE_DATE
     *
     * @return the value of employee_inf.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.CREATE_DATE
     *
     * @param createDate the value for employee_inf.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}